included:
  - Sources
  - NotariTests

excluded:
  - build
  - DerivedData
  - .build
  - Sources/Notari/Resources

disabled_rules:
  - todo
  - trailing_comma

opt_in_rules:
  - empty_count
  - explicit_init
  - force_unwrapping
  - implicit_return
  - redundant_nil_coalescing
  - unused_import

line_length:
  warning: 140
  error: 200
  ignores_comments: true

identifier_name:
  excluded:
    - id
    - ok
    - to
    - up
    - x
    - y
    - z

type_name:
  min_length: 3
  max_length: 60
